version: "2"


services: 
  db:
    image: postgres:9.6
    volumes: 
    - db:/var/lib/postgresql/data
    ports:
    - "5432:5432"
    environment:
    - POSTGRES_HOST_AUTH_METHOD=trust
    networks: ['mynetwork']
  web:
    build: .
    ports: 
      - "3000:3000"
    depends_on:
            - db
  
networks: {mynetwork: {}}
volumes:
  db: {}